// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7kHO5dSsOchYkcw4OxIYQR837pdFWJXg',
    appId: '1:621828999019:web:6bfc7b6b9d0c328a236e2e',
    messagingSenderId: '621828999019',
    projectId: 'hungrybelt-67484',
    authDomain: 'hungrybelt-67484.firebaseapp.com',
    storageBucket: 'hungrybelt-67484.firebasestorage.app',
    measurementId: 'G-V77H5DTMPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsGVApW366xneNU7HJfLYwaZU0TM3l888',
    appId: '1:621828999019:android:eb434eb8270c8ff7236e2e',
    messagingSenderId: '621828999019',
    projectId: 'hungrybelt-67484',
    storageBucket: 'hungrybelt-67484.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADqWIECYqVmRvlukifF9xUWloZBknV6Ko',
    appId: '1:621828999019:ios:f720fcd158ca9fa7236e2e',
    messagingSenderId: '621828999019',
    projectId: 'hungrybelt-67484',
    storageBucket: 'hungrybelt-67484.firebasestorage.app',
    iosBundleId: 'com.example.hungrybeltfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADqWIECYqVmRvlukifF9xUWloZBknV6Ko',
    appId: '1:621828999019:ios:f720fcd158ca9fa7236e2e',
    messagingSenderId: '621828999019',
    projectId: 'hungrybelt-67484',
    storageBucket: 'hungrybelt-67484.firebasestorage.app',
    iosBundleId: 'com.example.hungrybeltfinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7kHO5dSsOchYkcw4OxIYQR837pdFWJXg',
    appId: '1:621828999019:web:4252972422e8bae7236e2e',
    messagingSenderId: '621828999019',
    projectId: 'hungrybelt-67484',
    authDomain: 'hungrybelt-67484.firebaseapp.com',
    storageBucket: 'hungrybelt-67484.firebasestorage.app',
    measurementId: 'G-23VT3WFPJP',
  );

}